version: "3.9"
services:
  spigot:
    container_name: bitquest
    build: .
    volumes:
      - "./target/BitQuest.jar:/spigot/plugins/BitQuest.jar"
    ports:
      - "25565:25565"
    environment:
      - BITQUEST_NODE_HOST=btcd
  redis:
    image: redis
  btcd:
    image: explodi/btcd
